<?php
require_once( '/../fonctions.php'); 
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-08 at 17:24:30.
 */
class MesFonctionsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MesFonctions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MesFonctions;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert () == 20.
     *
     * @covers MesFonctions::donneNbArtistes
     */
    public function testDonneNbArtistes() {
        $this->assertEquals(
                20
                , MesFonctions::donneNbArtistes()
        );
    }

    /**
     * Generated from @assert () == 117.
     *
     * @covers MesFonctions::donneNbArtistes
     */
    public function testDonneNbArtistes2() {
        $this->assertEquals(
                117
                , MesFonctions::donneNbArtistes()
        );
    }

    /**
     * Generated from @assert (0, 0) == 0.
     *
     * @covers MesFonctions::add
     */
    public function testAdd() {
        $this->assertEquals(
                0
                , MesFonctions::add(0, 0)
        );
    }

    /**
     * Generated from @assert (1, 2) == 3.
     *
     * @covers MesFonctions::add
     */
    public function testAdd2() {
        $this->assertEquals(
                3
                , MesFonctions::add(1, 2)
        );
    }

    /**
     * Generated from @assert (6, 2) == 10.
     *
     * @covers MesFonctions::add
     */
    public function testAdd3() {
        $this->assertEquals(
                10
                , MesFonctions::add(6, 2)
        );
    }

    /**
     * @covers MesFonctions::connection
     * @todo   Implement testConnection().
     */
    public function testConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
